#pragma once

#include "gd32h7xx.h"
#include <stdio.h>

#define CONSOLE_USARTX_MODE 0

#define CONSOLE_USARTX USART0
#define CONSOLE_USART_CLK RCU_USART0
#define CONSOLE_USART_BAUDRATE 115200
#define CONSOLE_USART_GPIO_APBXCLKCMD rcu_periph_clock_enable
#define CONSOLE_USART_GPIO_CLK_TX RCU_GPIOA
#define CONSOLE_USART_GPIO_CLK_RX RCU_GPIOA
#define CONSOLE_USART_TX_GPIO_PORT GPIOA
#define CONSOLE_USART_TX_GPIO_PIN GPIO_PIN_9
#define CONSOLE_USART_RX_GPIO_PORT GPIOA
#define CONSOLE_USART_RX_GPIO_PIN GPIO_PIN_10
#define CONSOLE_USART_TX_RX_GPIO_AF GPIO_AF_7

#define CONSOLE_USART_IRQ USART0_IRQn
#define CONSOLE_USART_IRQ_HANDLER USART0_IRQHandler

void console_init(void);
